apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- hello/

replicas:
- name: hello
  count: 1

## 이미지 변경 및 버전 수정
images:
- name: nginxdemos/hello
  newName: nginx
  newTag: "latest"
